-- MySQL Script generated by MySQL Workbench
-- Fri Mar 10 17:04:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Address` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Address` (
  `idAddress` INT NOT NULL,
  `street` CHAR NULL,
  `additionalAddress` CHAR NULL,
  `postalCode` CHAR NULL,
  `city` CHAR NULL,
  PRIMARY KEY (`idAddress`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PointOfSale`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`PointOfSale` ;

CREATE TABLE IF NOT EXISTS `mydb`.`PointOfSale` (
  `idPointOfSale` INT NOT NULL,
  `namePointOfSale` CHAR NULL,
  `siret` CHAR NULL,
  `Address_idAddress` INT NOT NULL,
  `Manager_idUser` INT NOT NULL,
  PRIMARY KEY (`idPointOfSale`),
  INDEX `fk_PointOfSale_Address_idx` (`Address_idAddress` ASC) VISIBLE,
  INDEX `fk_PointOfSale_User1_idx` (`Manager_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_PointOfSale_Address`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `mydb`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PointOfSale_User1`
    FOREIGN KEY (`Manager_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `idUser` INT NOT NULL,
  `lastName` CHAR NULL,
  `firstName` CHAR NULL,
  `dateCreateAccount` DATE NULL,
  `phoneNumber` CHAR NULL,
  `username` CHAR NULL,
  `password` CHAR NULL,
  `email` CHAR NULL,
  `Address_idAddress` INT NOT NULL,
  `WorkPointOfSale_idPointOfSale FK` INT NOT NULL,
  PRIMARY KEY (`idUser`),
  INDEX `fk_User_Address1_idx` (`Address_idAddress` ASC) VISIBLE,
  INDEX `fk_User_PointOfSale1_idx` (`WorkPointOfSale_idPointOfSale FK` ASC) VISIBLE,
  CONSTRAINT `fk_User_Address1`
    FOREIGN KEY (`Address_idAddress`)
    REFERENCES `mydb`.`Address` (`idAddress`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_PointOfSale1`
    FOREIGN KEY (`WorkPointOfSale_idPointOfSale FK`)
    REFERENCES `mydb`.`PointOfSale` (`idPointOfSale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Order` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `dateOrder` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `dateDelivery` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
  `statusOrder` CHAR NOT NULL,
  `payMethod` CHAR NULL,
  `amountHT` FLOAT NULL,
  `amountTTC` FLOAT NULL,
  `Client_idUser` INT NOT NULL,
  `Pizzaiolo_idUser1` INT NOT NULL,
  `DeliverMan_idUser2` INT NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `fk_Order_User1_idx` (`Client_idUser` ASC) VISIBLE,
  INDEX `fk_Order_User2_idx` (`Pizzaiolo_idUser1` ASC) VISIBLE,
  INDEX `fk_Order_User3_idx` (`DeliverMan_idUser2` ASC) VISIBLE,
  CONSTRAINT `fk_Order_User1`
    FOREIGN KEY (`Client_idUser`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_User2`
    FOREIGN KEY (`Pizzaiolo_idUser1`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Order_User3`
    FOREIGN KEY (`DeliverMan_idUser2`)
    REFERENCES `mydb`.`User` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `idProduct` INT NOT NULL,
  `nameProduct` CHAR NULL,
  `size` CHAR NULL,
  `composition` CHAR NULL,
  `category` CHAR NULL,
  `unitPriceHT` FLOAT NULL,
  `unitPriceTTC` FLOAT NULL,
  `recipe` CHAR NULL,
  PRIMARY KEY (`idProduct`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredient`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Ingredient` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Ingredient` (
  `idIngredient` INT NOT NULL,
  `name` CHAR NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idIngredient`),
  INDEX `fk_Ingredient_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Ingredient_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Stock` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Stock` (
  `idStock` INT NOT NULL,
  `datePurchase` DATE NULL,
  `dateExpiration` DATE NULL,
  `PointOfSale_idPointOfSale` INT NOT NULL,
  PRIMARY KEY (`idStock`),
  INDEX `fk_Stock_PointOfSale1_idx` (`PointOfSale_idPointOfSale` ASC) VISIBLE,
  CONSTRAINT `fk_Stock_PointOfSale1`
    FOREIGN KEY (`PointOfSale_idPointOfSale`)
    REFERENCES `mydb`.`PointOfSale` (`idPointOfSale`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`assoc_Order_Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`assoc_Order_Product` ;

CREATE TABLE IF NOT EXISTS `mydb`.`assoc_Order_Product` (
  `Order_idOrder PFK` INT NOT NULL,
  `Product_idProduct PFK` INT NOT NULL,
  `quantity` INT NULL,
  INDEX `fk_assoc_Order_Product_Order1_idx` (`Order_idOrder PFK` ASC) VISIBLE,
  INDEX `fk_assoc_Order_Product_Product1_idx` (`Product_idProduct PFK` ASC) VISIBLE,
  CONSTRAINT `fk_assoc_Order_Product_Order1`
    FOREIGN KEY (`Order_idOrder PFK`)
    REFERENCES `mydb`.`Order` (`idOrder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assoc_Order_Product_Product1`
    FOREIGN KEY (`Product_idProduct PFK`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`assoc_Ingredient_Stock`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`assoc_Ingredient_Stock` ;

CREATE TABLE IF NOT EXISTS `mydb`.`assoc_Ingredient_Stock` (
  `Stock_idStock PFK` INT NOT NULL,
  `Ingredient_idIngredient PFK` INT NOT NULL,
  `quantityRemaining` INT NULL,
  `unit` CHAR NULL,
  INDEX `fk_assoc_Ingredient_Stock_Stock1_idx` (`Stock_idStock PFK` ASC) VISIBLE,
  INDEX `fk_assoc_Ingredient_Stock_Ingredient1_idx` (`Ingredient_idIngredient PFK` ASC) VISIBLE,
  CONSTRAINT `fk_assoc_Ingredient_Stock_Stock1`
    FOREIGN KEY (`Stock_idStock PFK`)
    REFERENCES `mydb`.`Stock` (`idStock`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_assoc_Ingredient_Stock_Ingredient1`
    FOREIGN KEY (`Ingredient_idIngredient PFK`)
    REFERENCES `mydb`.`Ingredient` (`idIngredient`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
